name: 'OMNeT++ Wasm Builder'
description: 'Build your OMNeT++ simulation model for WebAssembly'
inputs:
  config-file:
    description: 'your build.toml file path'
    required: false
    default: '/github/workspace/build.toml'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/zigen/omnetpp-wasm:latest'
  entrypoint: '/root/entrypoint.sh'
  args:
    - ${{ inputs.config-file }}
