name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Extract submodule hashes
        run: |
          echo qtbase_hash=$(git ls-tree HEAD qtbase | tr -s "\t" " " | cut -f 3 -d" ") >> $GITHUB_ENV
          echo omnetpp_hash=$(git ls-tree HEAD omnetpp | tr -s "\t" " " | cut -f 3 -d" ") >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: |
              qtbase/qtbase
              omnetpp/lib
              omnetpp/Makefile.inc
          key: qtbase-${{ env.qtbase_hash }}-omnetpp-${{ env.omnetpp_hash }}-${{ secrets.CACHE_VERSION }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.ci
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          outputs: type=docker,dest=/tmp/omnetpp-wasm.tar
      - name: Load image
        run: |
          docker images -a
          docker load --input /tmp/omnetpp-wasm.tar
      - name: Move Cache from image
        run: |
          docker run -t -v $(pwd):/usr/app ghcr.io/${{ github.repository }}:${{ github.sha }} bash -c "cp -R /root/omnetpp/lib /root/omnetpp/Makefile.inc /usr/app/omnetpp/ && cp -R /root/qtbase/qtbase /usr/app/qtbase/"
          ls -la
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: omnetpp-wasm-image
          path: /tmp/omnetpp-wasm.tar
  example-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: omnetpp-wasm-image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/omnetpp-wasm.tar
      - name: Build Example
        run: |
          docker run -t -v $(pwd):/usr/app -w /usr/app ghcr.io/${{ github.repository }}:${{ github.sha }} bash build_samples.sh
          ls -la public
      - name: Publish
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  push-to-registry:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) }}
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: omnetpp-wasm-image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/omnetpp-wasm.tar
      - name: Push Image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}:latest

