name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Extract submodule hashes
        run: |
          echo qtbase_hash=`git ls-tree HEAD qtbase | tr -s "\t" " " | cut -f 3 -d" "` >> $GITHUB_ENV
          echo omnetpp_hash=`git ls-tree HEAD omnetpp | tr -s "\t" " " | cut -f 3 -d" "` >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: |
              qtbase/qtbase
              omnetpp/out
              omnetpp/lib
              omnetpp/Makefile.inc
          key: qtbase-${{ env.qtbase_hash }}-omnetpp-${{ env.omnetpp_hash }}-${{ secrets.CACHE_VERSION }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.ci
          outputs: type=docker,dest=/tmp/omnetpp-wasm.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: omnetpp-wasm-image
          path: /tmp/omnetpp-wasm.tar
  example-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: omnetpp-wasm-image
          path: /tmp/omnetpp-wasm.tar
      -
        name: Load image
        run: |
          docker load --input /tmp/omnetpp-wasm.tar
          docker image ls -a
  push-to-registry:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: omnetpp-wasm-image
          path: /tmp/omnetpp-wasm.tar
      -
        name: Load image
        run: |
          docker load --input /tmp/omnetpp-wasm.tar
          docker image ls -a


