name: CI

on:
  push:
    branches: [ master, setup-ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          cp .bashrc .github/actions/build/
          rm -rf opp_bin/*
      - name: Build All
        uses: ./.github/actions/build
      - name: cache
        run: |
          ls omnetpp
          ls omnetpp/out

