name: build
on:
  push:
    branches: [ master, setup-ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Extract submodule hashes
        run: |
          echo qtbase_hash=`git ls-tree HEAD qtbase | tr -s "\t" " " | cut -f 3 -d" "` >> $GITHUB_ENV
          echo omnetpp_hash=`git ls-tree HEAD omnetpp | tr -s "\t" " " | cut -f 3 -d" "` >> $GITHUB_ENV
      - name: Copy files
        run: cp .bashrc .github/workflows/
      - uses: actions/cache@v2
        with:
          path: |
              qtbase/qtbase
              omnetpp/out
              omnetpp/lib
              omnetpp/Makefile.inc
          key: qtbase-${{ env.qtbase_hash }}-omnetpp-${{ env.omnetpp_hash }}-${{ secrets.CACHE_VERSION }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: docker.pkg.github.com/${{ github.repository }}/my-image:${{ github.ref }}
          outputs: type=docker,dest=/tmp/omnetpp-wasm.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: myimage
          path: /tmp/omnetpp-wasm.tar


